/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current active build summary */
        get: operations["getActiveBuild"];
        put?: never;
        /** Import a build (PoB code/XML or account+character) */
        post: operations["importBuild"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The core call — clipboard item vs equipped, under inferred assumptions */
        post: operations["diffItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rank pasted/stored items by score delta (Tier 3) */
        post: operations["scanStash"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/breakdown/{diff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tier-2/3 detail for a previous diff */
        get: operations["getBreakdown"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BuildSummary: {
            build_id: string;
            character_class: string;
            ascendancy?: string;
            level: number;
            main_skill: {
                name: string;
                /** @description false if user overrode */
                inferred: boolean;
                confidence?: number;
            };
            /** @enum {string} */
            preset_default: "mapping" | "bossing" | "balanced";
        };
        Assumption: {
            /** @description Stable rule id from assumptions/rules */
            id: string;
            /** @description Chip text */
            label: string;
            value: unknown;
            /** @description Materially affected this verdict */
            impactful: boolean;
            /** @constant */
            reversible: true;
            source_rule?: string;
        };
        VerdictCard: {
            diff_id: string;
            /** @enum {string} */
            verdict: "UPGRADE" | "SIDEGRADE" | "DOWNGRADE" | "CANT_EVALUATE";
            offense_delta_pct: number;
            defense_delta_pct: number;
            /** @description Doctrine I2 cap */
            sentence: string;
            assumptions: components["schemas"]["Assumption"][];
            confidence: number;
            cant_evaluate_reasons?: string[];
            /** @enum {string} */
            preset: "mapping" | "bossing" | "balanced";
            /** @description Engine time; I6 telemetry */
            compute_ms?: number;
        };
        Breakdown: {
            diff_id: string;
            /** @description Tier-2 — mods ranked by contribution to the delta */
            drivers: {
                mod_text: string;
                contribution_pct: number;
                /** @description e.g. total_dps */
                stat: string;
            }[];
            /** @description Tier-3 — raw engine breakdown tree (schema owned by engine/) */
            pob_breakdown?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getActiveBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSummary"];
                };
            };
            /** @description No build imported */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importBuild: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description PoB share code or raw XML */
                    pob_code?: string;
                    account?: string;
                    character?: string;
                } & (unknown | unknown);
            };
        };
        responses: {
            /** @description Imported */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildSummary"];
                };
            };
            /** @description Unparseable build */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    diffItem: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Raw Ctrl+C clipboard text (untrusted) */
                    item_text: string;
                    /**
                     * @description Omit to use build default
                     * @enum {string}
                     */
                    preset?: "mapping" | "bossing" | "balanced";
                    /** @description One-tap assumption flips (Doctrine I3) */
                    overrides?: {
                        assumption_id: string;
                        value: unknown;
                    }[];
                };
            };
        };
        responses: {
            /** @description Verdict */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerdictCard"];
                };
            };
            /** @description No active build */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Item text unparseable */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    scanStash: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    items: string[];
                    /** @enum {string} */
                    preset?: "mapping" | "bossing" | "balanced";
                };
            };
        };
        responses: {
            /** @description Ranked results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        results: {
                            index: number;
                            verdict: components["schemas"]["VerdictCard"];
                        }[];
                    };
                };
            };
        };
    };
    getBreakdown: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full mod-level delta tree + raw PoB breakdown reference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Breakdown"];
                };
            };
            /** @description Expired or unknown diff_id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
