"""Deterministic six-level degradation ladder for unattended operation."""
from __future__ import annotations

import json
import os
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any


LEVEL_NAMES = {
    0: "nominal",
    1: "route_throttled",
    2: "low_cost_tier_gone",
    3: "frontier_constrained",
    4: "judgment_constrained",
    5: "drain",
    6: "halt",
}


@dataclass(frozen=True)
class DegradationSignals:
    """Mechanically observed inputs; highest active trigger wins."""

    route_over_schedule: bool = False
    allowance_unknown_or_stale: bool = False
    low_cost_exhausted: bool = False
    frontier_warning: bool = False
    pm_constrained: bool = False
    hard_stop_near: bool = False
    dead_letters_elevated: bool = False
    budgets_exhausted: bool = False
    unrecoverable_main: bool = False
    telemetry_lost: bool = False
    safety_violation: bool = False


@dataclass(frozen=True)
class DegradationVerdict:
    level: int
    name: str
    behavior: str
    reasons: tuple[str, ...]


BEHAVIORS = {
    0: "normal roles; dynamic concurrency",
    1: "queue eligible work; fallback for critical tasks only",
    2: "critical work on frontier within reserve; reduce concurrency",
    3: "critical path and repair only; park optional work",
    4: "scheduler drains unambiguous queue; defer new intake",
    5: "open nothing new; finish, validate, merge or revert in flight",
    6: "write run report; set HALT; preserve all state",
}


def evaluate(signals: DegradationSignals) -> DegradationVerdict:
    """Evaluate one point in a timeline; recovery naturally lowers the level."""
    reasons: list[str] = []
    level = 0
    triggers = (
        (1, signals.route_over_schedule, "provider over scheduled burn"),
        (1, signals.allowance_unknown_or_stale, "allowance unknown or stale"),
        (2, signals.low_cost_exhausted, "low-cost tier exhausted"),
        (3, signals.frontier_warning, "frontier capacity over warning"),
        (4, signals.pm_constrained, "PM capacity constrained"),
        (5, signals.hard_stop_near, "hard stop near"),
        (5, signals.dead_letters_elevated, "dead letters elevated"),
        (6, signals.budgets_exhausted, "budgets exhausted"),
        (6, signals.unrecoverable_main, "unrecoverable main failure"),
        (6, signals.telemetry_lost, "telemetry loss"),
        (6, signals.safety_violation, "safety violation"),
    )
    for candidate, active, reason in triggers:
        if active:
            level = max(level, candidate)
            reasons.append(reason)
    return DegradationVerdict(level, LEVEL_NAMES[level], BEHAVIORS[level], tuple(reasons))


@dataclass
class RunReportData:
    budget_by_role_day: dict[str, dict[str, Any]] = field(default_factory=dict)
    tasks_landed: list[str] = field(default_factory=list)
    dead_letters: list[dict[str, Any]] = field(default_factory=list)
    open_prs: list[dict[str, Any]] = field(default_factory=list)


def _table_or_empty(rows: list[list[Any]], headers: list[str]) -> list[str]:
    output = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    if not rows:
        rows = [["none"] + ["" for _ in headers[1:]]]
    output.extend("| " + " | ".join(str(cell) for cell in row) + " |" for row in rows)
    return output


def render_run_report(data: RunReportData, history: list[dict[str, Any]]) -> str:
    """Render every artifact section required when the ladder reaches Level 6."""
    budget_rows = [
        [role, day, json.dumps(values, sort_keys=True)]
        for role, days in sorted(data.budget_by_role_day.items())
        for day, values in sorted(days.items())
    ]
    dead_rows = [
        [item.get("task_id", ""), item.get("last_error_fingerprint", "")]
        for item in data.dead_letters
    ]
    pr_rows = [[item.get("number", ""), item.get("head", ""), item.get("state", "")] for item in data.open_prs]
    history_rows = [
        [item.get("ts", ""), item.get("from_level", ""), item.get("to_level", ""), item.get("reasons", "")]
        for item in history
    ]
    lines = [
        "# RUN REPORT",
        "",
        "Generated by degradation Level 6 before HALT.",
        "",
        "## Budget consumed per role per day",
        "",
        *_table_or_empty(budget_rows, ["Role", "Day", "Consumed"]),
        "",
        "## Tasks landed",
        "",
        *(f"- {task}" for task in data.tasks_landed),
    ]
    if not data.tasks_landed:
        lines.append("- none")
    lines.extend([
        "",
        "## Dead letters and last error signatures",
        "",
        *_table_or_empty(dead_rows, ["Task", "Last error fingerprint"]),
        "",
        "## Pull requests left open",
        "",
        *_table_or_empty(pr_rows, ["PR", "Head", "State"]),
        "",
        "## Degradation-level history",
        "",
        *_table_or_empty(history_rows, ["Timestamp", "From", "To", "Reasons"]),
        "",
    ])
    return "\n".join(lines)


class DegradationController:
    """Track level transitions and perform the Level 6 artifact protocol."""

    def __init__(self, mailroom: str | Path, *, now=time.time) -> None:
        self.mailroom = Path(mailroom)
        self._now = now
        self._level = 0
        self.history: list[dict[str, Any]] = []

    def level(self) -> int:
        return self._level

    def step(
        self,
        signals: DegradationSignals,
        *,
        report_data: RunReportData | None = None,
    ) -> DegradationVerdict:
        verdict = evaluate(signals)
        if verdict.level != self._level:
            self.history.append({
                "ts": self._now(),
                "from_level": self._level,
                "to_level": verdict.level,
                "reasons": "; ".join(verdict.reasons) or "recovered",
            })
            self._level = verdict.level
        if verdict.level == 6:
            self._halt_with_report(report_data or RunReportData())
        return verdict

    def _halt_with_report(self, data: RunReportData) -> None:
        self.mailroom.mkdir(parents=True, exist_ok=True)
        report = self.mailroom / "RUN-REPORT.md"
        temporary = report.with_suffix(".md.tmp")
        temporary.write_text(render_run_report(data, self.history), encoding="utf-8")
        os.replace(temporary, report)
        (self.mailroom / "HALT").touch(exist_ok=True)


def arbiter_after_circuit_break(
    config: dict[str, Any], *, current: str = "pm", circuit_broken: set[str] | None = None
) -> str | None:
    """Resolve the declared arbiter fallback; caller performs the promotion."""
    broken = circuit_broken or set()
    if current not in broken:
        return current
    fallback = config.get("arbiter_fallback")
    return fallback if isinstance(fallback, str) and fallback not in broken else None


def signals_dict(signals: DegradationSignals) -> dict[str, bool]:
    """Stable serialization used by run reports and simulation diagnostics."""
    return asdict(signals)
